name: Publish Docker
on:
  workflow_run:
    workflows: ["PR Code Quality Checks"] # 🌟 This must exactly match the 'name:' in your pr-checks.yml
    types:
      - completed
    branches:
      - main # Ensures it only triggers after main branch checks complete

jobs:
  github-repo:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: rajasekhar-gundala/markreply
        username: ${{ github.actor }}
        password: ${{ secrets.PERSONAL_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile
        buildoptions: "--compress --force-rm"
        tags: "latest"